// Test de Operaciones Aritméticas para Backend
(defun main ()
  (princ "Suma: ")
  (princ (+ 10 5))
  (princ " Resta: ")
  (princ (- 10 5))
  (princ " Multi: ")
  (princ (* 10 5))
  (princ " Div: ")
  (princ (/ 10 2))
  (princ " Mod: ")
  (princ (mod 10 3))
  
  (princ " Logica AND: ")
  (princ (and 1 0))
  (princ " Logica OR: ")
  (princ (or 1 0))
  (princ " Logica NOT: ")
  (princ (not 0))
  
  (princ " EQ: ")
  (princ (= 5 5))
  (princ " NEQ: ")
  (princ (/= 5 4))
  (princ " LT: ")
  (princ (< 3 5))
  (princ " GT: ")
  (princ (> 5 3))
  (princ " LEQ: ")
  (princ (<= 5 5))
  (princ " GEQ: ")
  (princ (>= 5 5))
)

(main)
